# Default values for workspace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

username: user1

workbench: my-workbench

subdomain: apps.cluster-guid.sandbox.opentlc.com

minio:
  user: minio
  pass: minio123
  host: minio.minio.svc.cluster.local
  bucket: user1
  route_prefix: "https://minio-s3-minio"